"""
Workflow event handlers and utilities.
"""
from collections.abc import AsyncIterable
from typing import cast

from agent_framework import (
    Agent,
    AgentResponse,
    Message,
    WorkflowEvent,
    WorkflowRunState,
    tool
)
from agent_framework.orchestrations import HandoffAgentUserRequest

async def drain_events(stream: AsyncIterable[WorkflowEvent]) -> list[WorkflowEvent]:
    """
    Collect all events from an async stream into a list.
    
    This helper drains the workflow's event stream so we can process events
    synchronously after each workflow step completes.
    
    Args:
        stream: Async iterable of WorkflowEvent
        
    Returns:
        List of all events from the stream
    """
    return [event async for event in stream]


def print_agent_responses(request: AgentResponse) -> None:
    """
    Display agent responses since the last user message in a handoff request.
    
    The HandoffUserInputRequest contains the full conversation history so far,
    allowing the user to see what's been discussed before providing their next input.
    
    Args:
        request: The user input request containing conversation and prompt
    """
    if not request.messages:
        return
    
    # Reverse iterate to collect agent responses since last user message
    agent_responses: list[Message] = []
    for message in request.messages[::-1]:
        if message.role == "user":
            break
        agent_responses.append(message)
    
    # Print agent responses in original order
    agent_responses.reverse()
    for message in agent_responses:
        speaker = message.author_name or message.role.value
        print(f"  {speaker}: {message.text}")


def handle_workflow_events(events: list[WorkflowEvent], verbose: bool = True) -> list[WorkflowEvent[HandoffAgentUserRequest]]:
    """
    Process workflow events and extract any pending user input requests.
    
    This function inspects each event type and:
    - Prints workflow status changes (IDLE, IDLE_WITH_PENDING_REQUESTS, etc.)
    - Displays final conversation snapshots when workflow completes
    - Prints user input request prompts
    - Collects all RequestInfoEvent instances for response handling
    
    Args:
        events: List of WorkflowEvent to process
        verbose: Whether to print detailed status information
        
    Returns:
        List of RequestInfoEvent representing pending user input requests
    """
    requests: list[WorkflowEvent[HandoffAgentUserRequest]] = []
    
    for event in events:
        if event.type == "handoff_sent":
            # handoff_sent event: Indicates a handoff has been initiated
            print(f"\n[Handoff from {event.data.source} to {event.data.target} initiated.]")
        elif event.type == "status" and event.state in {
            WorkflowRunState.IDLE,
            WorkflowRunState.IDLE_WITH_PENDING_REQUESTS,
        }:
            # Status event: Indicates workflow state changes
            print(f"\n[Workflow Status] {event.state}")
        elif event.type == "output":
            # Output event: Contains contents generated by the workflow
            data = event.data
            if isinstance(data, AgentResponse):
                for message in data.messages:
                    if not message.text:
                        # Skip messages without text (e.g., tool calls)
                        continue
                    speaker = message.author_name or message.role
                    print(f"- {speaker}: {message.text}")
            elif event.type == "output":
                # The output of the handoff workflow is a collection of chat messages from all participants
                conversation = cast(list[Message], event.data)
                if isinstance(conversation, list):
                    print("\n=== Final Conversation Snapshot ===")
                    for message in conversation:
                        speaker = message.author_name or message.role
                        print(f"- {speaker}: {message.text or [content.type for content in message.contents]}")
                    print("===================================")
        elif event.type == "request_info" and isinstance(event.data, HandoffAgentUserRequest):
            print_agent_responses(event.data.agent_response)
            requests.append(cast(WorkflowEvent[HandoffAgentUserRequest], event))

    
    return requests
